### ISSUE TITLE
Returning 304

### ISSUE THREAD

**Issue by ReeSilva** [rendora/rendora#19]
Hey guys, I'm looking for u to see if anyone can help, because I tried a lot and nothing seems to work. I have the follow stack:
An AWS ECS Fargate Service exposing the Rendora (with cache disabled for test), in front of this a Load Balancer and in front of this Load Balancer I have Cloudfront also with cache disabled for test. This is my actual Rendora config:

```yaml
target:
  url: http://localhost:8080 #This is the address for the React SPA Application, Fargate doesn't use container linkings
backend:
  url: http://localhost:8080 #This is the address for the React SPA Application, Fargate doesn't use container linkings
headless:
  waitAfterDOMLoad: 3000
  internal:
    url: http://localhost:9222
cache:
  type: none
debug: true
server:
  enable: true
filters:
  userAgent:
    defaultPolicy: blacklist
    exceptions:
      keywords:
        - googlebot
        - Yahoo! Slurp
        - bingbot
        - yandex
        - baiduspider
        - facebookexternalhit
        - twitterbot
        - rogerbot
        - linkedinbot
        - embedly
        - quora link preview
        - showyoubot
        - outbrain
        - pinterest/0.
        - developers.google.com/+/web/snippet
        - slackbot
        - vkShare
        - W3C_Validator
        - redditbot
        - Applebot
        - WhatsApp
        - flipboard
        - tumblr
        - bitlybot
        - SkypeUriPreview
        - nuzzel
        - Discordbot
        - Google Page Speed
        - Qwantify
        - pinterestbot
        - Bitrix link preview
        - XING-contenttabreceiver
        - Chrome-Lighthouse'
        - laboritbot
```
When I call the Rendora API `/render` it works like a charm, when I reach my page through a browser, it works also. But, when I try to curl using one of my defined bots, it returns 304 everytime. I noticed that in browser the initial call also returns 304, but render oks, and on the API of Rendora it also renders even returning 304.

Is there anything that am I doing wrong?

Thank u in advance.
