### ISSUE TITLE
How to set up rendora with Firebase hosting?

### ISSUE THREAD

**Issue by oldirty91** [rendora/rendora#23]
Hello,

Could you provide some guidance on how to set up rendora to work with a SPA (vue, angular, react, etc.)  served from a static source such as firebase hosting or an AWS bucket? 

Thanks,
Tom

**Comment by zicklag** [comment]
I don't have a lot of time, but here are my quick thoughts:

What you will have to do is run Rendora and a headless chrome instance on your own server. You can find a Docker compose YAML in the documentation I think. You will need to then point your DNS to the server running Rendora. All requests to your app will proxy through Rendora. The Rendora config file could look something like this:

```yaml
# Both of these need to point to the domain that is hosting your site.
# Note you will need your static files hosted under a different domain than your main
# site, because the main site needs to point to Rendora.
target:
  url: http://my_s3_hosted_site.com
backend:
  url: http://my_s3_hosted_site.com

headless:
  waitAfterDOMLoad: 1000 # This tell Rendora how long to wait for the page to fully render
  internal:
    #  This needs to be accessible from the server running Rendora and needs
    # to point to the headless chrome instance
    url: 'http://headless:9222'

# The rest of this is general Rendora config.
  blockedURLs:
   - "*.png"
   - "*.jpg"
   - "*.jpeg"
   - "*.webp"
   - "*.gif"
   - "*.woff2"
   - "*.svg"
   - "*.woff"
   - "*.ttf"
   - "https://www.youtube.com/*"
   - "https://www.google-analytics.com/*"
   - "https://fonts.googleapis.com/*"

filters:
  userAgent:
    defaultPolicy: blacklist
    exceptions:
      keywords:
        - bot
        - slurp
        - bing
        - crawler
        - discourse
        - rocketchat
        - facebook
        - twitter
```

Hope that helps if you have specific questions I might find time to answer them. :)
