### ISSUE TITLE
Add sitemap.xml as paths example

### ISSUE THREAD

**Issue by fabien-michel** [rendora/rendora#27]
XML files are HTML'ized by chrome headless. Which means that the result is not the original xml. It is a problem with sitemap.xml which need to stay in XML format (for google bot to index it). As this is a common issue I suggest to add this to configuration example:
```yaml

filters:
    userAgent:
        defaultPolicy: blacklist
        exceptions:
            keywords:
                - bot
                - slurp
                - bing
                - crawler
                - baiduspider
    paths:
        defaultPolicy: whitelist
        exceptions:
            exact:
                - /sitemap.xml
```

Or eventually a warning some where in the documentation
