### ISSUE TITLE
Running rendora from docker does not work. docker: Error response from daemon: create ./CONFIG_FILE.yaml

### ISSUE THREAD

**Issue by AlexanderTserkovniy** [rendora/rendora#29]
Steps to repro:

Run the command from documentation
`docker run --net=host -v ./CONFIG_FILE.yaml:/etc/rendora/config.yaml rendora/rendora`

What I have tried:

1. git clone repo && cd to config_examples && run with `docker run --net=host -v ./CONFIG_FILE.yaml:/etc/rendora/config.yaml rendora/rendora`
Return value is
docker: Error response from daemon: create ./CONFIG_FILE.yaml: "./CONFIG_FILE.yaml" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
See 'docker run --help'.

2. git clone repo && cd to config_examples && `docker run --net=host -v config.yml:/etc/rendora/config.yml rendora/rendora`
Return value is
`error: read /etc/rendora/config.yml: is a directory`

3. git clone repo && `docker run --net=host --mount source=config_examples,target=/etc/rendora/ rendora/rendora 
error: Config File "config" Not Found in "[/rendora /etc/rendora]"`

Docker 2.1.0.4
Engine 19.03.4
Channel stable

**Comment by Dijir** [comment]
docker run --net=host -v $(pwd)/CONFIG_FILE.yaml:/etc/rendora/config.yaml rendora/rendora

**Comment by AlexanderTserkovniy** [comment]
```
config_examples % docker run --net=host -v $(pwd)/CONFIG_FILE.yaml:/etc/rendora/config.yaml rendora/rendora
error: read /etc/rendora/config.yaml: is a directory
```

**Comment by Dijir** [comment]
I got this issue today and I got It working with the $(pwd). I've used this exact command.
Are you using Docker on Windows?

I've created docker-compose.yml with the rendora, Chrome headless and nginx services. It works too.

**Comment by AlexanderTserkovniy** [comment]
Using it on mac. May you attach the `docker-compose.yml` to the thread?

**Comment by Dijir** [comment]
**docker-compose.yml**:
```
version: '3'
services:
  nginx:
    restart: always
    image: nginx
    volumes:
    - ./dist:/var/www/html
    - ./nginx/sites:/etc/nginx/conf.d
    - ./nginx/logs:/var/log/nginx
    ports:
    - 8000:80

  headless:
    image: rendora/chrome-headless:latest
    tmpfs:
    - /tmp

  rendora:
    image: rendora/rendora
    volumes:
    - ./config.yaml:/etc/rendora/config.yaml
    ports:
    - 3001:3001
    - 9242:9242
    depends_on:
    - headless
```

**config.yaml**:
```
listen:
    port: 3001

backend:
    url: http://nginx

target:
    url: http://nginx
    
headless:
  internal:
    url: http://headless:9222

cache:
    type: none

filters:
    userAgent:
        defaultPolicy: whitelist

server:
  enable: true
```

**Comment by joket1999** [comment]
It doesn't  work.

```sh
docker run -it -d --net=host -v /usr/CONFIG_FILE.yaml:/etc/rendora/config.yaml rendora/rendora
```

config.yaml

```yaml
target:
    url: "http://test.com" 
backend:
    url: "http://test.com"

filters:
    userAgent:
        defaultPolicy: blacklist
        exceptions:
            keywords:
                - bot
                - slurp
                - bing
                - crawler
```
result:
CONTAINER ID | IMAGE | COMMAND| CREATED | STATUS | PORTS | NAMES
------ | ------- | --- | ---- | ----- | ---- | -----
198af5d83797 | rendora/rendora | "rendora" | 11 seconds ago | Exited (1) 3 seconds ago |  | vigorous_blackburn
