### ISSUE TITLE
ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by codinglobster** [rendora/rendora#34]
with the configuration down below, everything looks just fine,but when I visit `http://localhost:3001/`, I only got  `**ERR_CONNECTION_REFUSED**`, can anyone told me how to debug with it, a lot of thanks.

**chrome-headless** 
![image](https://user-images.githubusercontent.com/22992734/75559422-624fd680-5a7e-11ea-814a-4b504db3591e.png)

**rendora**
![image](https://user-images.githubusercontent.com/22992734/75559457-77c50080-5a7e-11ea-988a-53e3e2f12893.png)

**local react project** 
![image](https://user-images.githubusercontent.com/22992734/75559503-890e0d00-5a7e-11ea-9047-e70531c781ca.png)

**configuration**
```
listen:
    address: 0.0.0.0
    port: 3001
cache:
    type: redis
    timeout: 6000
    redis:
        address: localhost:6379
target:
    url: "http://127.0.0.1:3000" 
backend:
    url: "http://127.0.0.1:3000"
headless:
    waitAfterDOMLoad: 0
    internal:
      url: http://localhost:9222
output:
    minify: true
filters:
    userAgent:
        defaultPolicy: blacklist
        exceptions:
            keywords:
                - bot
                - slurp
                - bing
                - crawler
    paths:
        defaultPolicy: whitelist
        exceptions:
            prefix:
             - /users/
```
