### ISSUE TITLE
Question: running rendora docker together with a docker nginx container

### ISSUE THREAD

**Issue by ecerroni** [rendora/rendora#4]
First of all kudos for this awesome project. It solves an actual paint point while working with SPAs.

I have a custom setup I am not able to make work and I am wondering if it is even possible.

The VPS looks like this:

A docker container built from a custom nginx image that serves the react files.

The custom nginx image has a custom ngnix.conf copied to `/etc/nginx/nginx.conf` and the react dist files copied to `/var/www/html/myapp` at build time.

`docker run --name my-nginx-app -d --network my-network -p 80:80 my-custom-nginx-image`

Everything works but when I try to force SSR.

Just running rendora and the chrome headless images do nothing although I am able to render the SSR'ed content through the API, when enabled, posting to `/render`

What am I doing wrong?

**Comment by geokb** [comment]
Hey @ecerroni and thanks for the nice words, as for your issue, it's really hard to solve it all without seeing your rendora config file, it maybe because you didn't add any whitelisted user agent keywords since rendora works by default as a transparent reverse HTTP proxy and thus it only transmits initial response as is. You need to add something like


```yaml
filters:
    userAgent:
        defaultPolicy: blacklist
        exceptions:
            keywords:
                - bingbot
                - yandex
```


this will whitelist all useragents containing "bingbot" and "yandex" with ignoring case sensitivity. If you try it with curl for example


```bash
curl -A "BingBot" http://127.0.0.1:3001
```

You will get the SSR'ed page this time, note that rendora is listening by default to the port `3001`.



But tbh I believe that your problem maybe due to something else, do you have a backend server or your entire app is hosted by nginx itself (i.e. your entire app is contained within the react javascript files)? If this is the case I suggest you set rendora to be listening to the port `80` and make your nginx as your backend. You can then map your host port to another number such `4000` for example


```bash
docker run --name my-nginx-app -d --network my-network -p 4000:80 my-custom-nginx-image
```

and then in your rendora config file you set the backend and target urls to `http://127.0.0.1:4000` , so you can change your rendora yaml config file to something like 


```yaml
target:
    url: "http://127.0.0.1:4000"

backend:
    url: "http://127.0.0.1:4000"

```

and btw, it's much easier to use `docker-compose` instead of multiple `docker run` with having all your configurations in one place

```yaml
version: "3"
services:
    headless:
        image: rendora/chrome-headless:latest
        ports:
            - 127.0.0.1:9222:9222
        networks:
            - my-network
        tmpfs:
            - /tmp
    rendora:
        image: rendora/rendora
        network_mode: "host"
        volumes:
            - {YOUR_CONFIG_FILE}.yaml:/etc/rendora/config.yaml
    nginx:
        image: my-custom-nginx-image
        ports:
            - 127.0.0.1:4000:80
        networks:
            - my-network

networks:
    my-network:
```

and now you just run your entire stack with one command

```bash
docker-compose -f YOUR_DOCKER_COMPOSE_FILENAME up
```
